### PR TITLE
currency ticker optional fields

### PR DESCRIPTION
**Pull request by ngauthier**

### CODE REVIEW

**Comment by ngauthier** [comment]
@trestrantham @spencewood I wanted to be more explicit around which fields are optional. Currently, we require most fields but pass nulls to them. Here, I mark everything optional that could be omitted instead of being null or blank.

Because we may not have supply info, that is optional and so is market cap. Name and logo may also not be present.

Finally, in rare cases for very new currencies, we don't have a high value yet. This is a very tight race condition but possible.

Symbol (`currency`) and price are guaranteed. As well as price change, volume, and volume change for intervals.

**Comment by ngauthier** [comment]
@spencewood can you work your shipping magic? Or show me how?

**Comment by spencewood** [comment]
I'll ship it.

**Comment by spencewood** [comment]
@ngauthier published!

**Pull request merged**
