### PR TITLE
Initial setup of client

### PR DESCRIPTION
**Pull request by spencewood**
This is the JavaScript client for the ticker. I've copied over some of the types from the gateway and re-exposed them so they can be used there. This works as I expect when imported into the nomics.com codebase, and is 100% test covered. There really isn't a whole lot here, but I think this is a pretty good start. I think as we learn more about how this is used, we can do some more shifting of types and code around if needed.

One big thing I'll point out is that I opted for cross-fetch (https://github.com/lquixada/cross-fetch) for the fetch client. I haven't actually used this before, but I wanted to make sure this has the highest support. It actually uses `node-fetch` if needed or `whatwg-fetch` for the browser pollyfill. And it also works with React native too. Time will tell if this is a good option, but it will be super easy to swap out if it isn't since there is a single interface point for the fetch client.

### CODE REVIEW

**Comment by ngauthier** [comment]
This is great. I think one change I would want to make is the naming of the API methods. You named the currency ticker `nomics.currencies()` but we have a currencies endpoint:

https://api.nomics.com/v1/currencies?key=2018-09-demo-dont-deploy-b69315e440beb145

The ticker is under /v1/currencies/ticker. I think we should have some kind of reliable naming that can't have conflicts, for example, camel case of every component, e.g.:

`nomics.v1CurrenciesTicker()`

Or, if we are going to version the client in such a way that the client 1.x.x versions use api v1, and client 2.x.x versions use v2, etc, then we could drop the version and use:

`nomics.currenciesTicker()`

We could also namespace it like:

`nomics.currencies.ticker()`

but then what would the currencies endpoint be? `nomics.currencies()`? Might be confusing.

We could also conform to the Open API Spec's naming, which would make it:

`nomics.getCurrenciesTicker`

They don't use the version, but they do use the http method. Although since we only do GETs, and probably will for a long time, I don't think we need the get in every one.

@trestrantham check out this PR too, and lmk between the two of you what kind of naming standard would work well.

**Comment by spencewood** [comment]
Yeah, I did give this a bit of thought when I was putting it together, but I just wanted to get something out and figure out naming later. I realized right away that `.currencies` probably wasn't right since it didn't match the api path, but felt like `.currenciesTicker` might be too weird for users. I also wasn't really sure if we were going to extend this to add stuff like `/v1/currencies`.

If we tag on a version in there, I think it makes it really weird. I think I might prefer that to be a passed in option:

`.currenciesTicker({ version: 1 })`

Personally, I prefer the `get<X>()` approach to things, so `.getCurrenciesTicker()` sounds good to me. My only hesitation is just how verbose it is.

**Comment by trestrantham** [comment]
This looks great. In my pseudocode for this a few weeks ago, I used `currenciesTicker` so that's my vote but `getCurrenciesTicker` would be fine too IMO.

I think for the version, it could be set when instantiating the client like `const client = new Nomics({ apiKey: "key", version: 2 })` (or similar).

For tests, is it idiomatic to have them inline with the source? I put mine in `./test` because it felt cluttered, but just curious if there's a best practice there?

For the ticker value types, I think we can use `string` for all since we aren't doing any casting.

This is awesome! 😎

**Comment by spencewood** [comment]
Ok, I think I'll go with `currenciesTicker`! I think that makes the most sense. And having the version in the initial instance makes sense to me too. Even if you did need to access different versions of different endpoints, you'd just create multiple instances: `nomics1 = nomics({ version: 1, key })` and `nomics2 = nomics({ version 2, key})`.

For the tests, I just went with how they were done in the nomics.com codebase. I love having the tests close the the implementation (although I am a fan of the `__tests__` directory that jest pushes).

One more thing here is that this lib also does provide types out of the box too, so you can see the types in VS code just by importing and using the library. Pretty nifty. Actually, the one thing that is weird here is that the interval keys *do not* show up for I'm guess multiple reasons: first, they start with a number (1d), and you have to use the bracket syntax to access them. Second is that they're optional. Anyway, no biggie right now, and perhaps addressable later.

**Comment by spencewood** [comment]
Sorry, one more thing. I saw that you used `new` in your example. I was thinking about that too, and whether that was expected or not. I think it might be. Right now I have a function factory that just returns a new api object, so: `const n = nomics({ /* options */ })` rather than `const n = new Nomics({ /* options */ })`. I actually probably could support both, but using new here gives it more of an inherent understanding that you are creating a new instance.

**Comment by ngauthier** [comment]
Sounds great all around.

Pick one way to do the constructor and we can stick to it.

**Comment by ngauthier** [comment]
What is the publish process like? How do we publish JS and TS together? Or are we not there yet?

**Comment by spencewood** [comment]
The build of this project generates a `/dist` folder with everything transpiled, including the .d.ts files. The `main` of the package.json points to the dist. So, really just `npm publish` should do what we need. I'll of course verify this right after. At some point soon, I'd like to get a workflow in place to test and release, but I can do it manually for the time being.

**Comment by ngauthier** [comment]
Awesome. Totally fine for us to release manually for a while, no rush on
automating that.

**Comment by ngauthier** [comment]
Also, we don't even have to cut releases right now, we can run it off
github master branch while we work on it, then cut a release when it's
stable.

**Comment by trestrantham** [comment]
I didn't even realize I did `new Nomics()` heh. But I do like that because it is explicit that you're creating a new instance.

**Comment by ngauthier** [comment]
I think I like it too. Even if we don't do much
initialization/customization, it gives us a place to add it in the future.

**Comment by spencewood** [comment]
Alright, the above items have been addressed:

* You use `new` when initializing now: `const nomics = new Nomics({ /* options */ });`
* `currencies` is now `currenciesTicker`
* Added `version` for the initializer (although it does nothing right now in the implementation)

**Comment by spencewood** [comment]
Moving forward here so I can make the changes in other spots that depend on this.

**Pull request merged**
